### ISSUE TITLE
Copy error during deployment from Linux

### ISSUE THREAD

**Issue by laguten** [egorshulga/oci-always-free-k8s#2]
I had following errors during the deployment through terraform apply:
![2022-02-01_11_12_46](https://user-images.githubusercontent.com/10452157/151950713-8a85a20e-0daf-40eb-b373-282bc5e0539f.png)

**Comment by egorshulga** [comment]
That's simple🙂: you enabled a `windows_overwrite_local_kube_config` variable, which copies a kube config into user folder (to enable kubectl commands without any params). Unfortunately, this command targets Windows OS. I think you'll need to disable this variable (in your variables.auto.tfvars file).
The file is also copied from the control plane, so we can use kubectl like the following: `kubectl  --kubeconfig .terraform/.kube/config-external` (when called from the root of the cloned repo after provisioning is complete)

**Comment by laguten** [comment]
Thank you. Now all right.

**Comment by egorshulga** [comment]
Great!
